### ISSUE TITLE
Issue with singular matrix during backward pass

### ISSUE THREAD

**Issue by AvivNavon** [marvin-eisenberger/implicit-sinkhorn#3]
Hi, thank you for this great work.
When trying to use the layer in my net, I'm getting an error during backward pass:

```
grad_ab = torch.linalg.solve(K, t)
torch._C._LinAlgError: torch.linalg.solve: (Batch element 13): The solver failed because the input matrix is singular.
```

Any suggestions on how to address this issue? This issue arises after some time of training the model.

**Comment by bytesnake** [comment]
you can switch to least-square for an ill-conditioned instance of `K`, for example like this

```python
try:
    grad_ab = torch.linalg.solve(K, t)
except:
    # switch to least-square solution for more stable results
    grad_ab = torch.linalg.lstsq(K, t)
    grad_ab = grad_ab.solution
```

**Comment by AvivNavon** [comment]
Thanks @bytesnake, will try that.
